name: Unit and E2E Test - Helm

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run Helm Unit Tests
        run: make helm-unittest

      - name: Install Helm
        run: make helm

      # Setup Kind (skip Kustomize deploy)
      - name: Setup Kind Cluster
        run: make test-e2e-setup-cluster INSTALL_METHOD=helm

      - name: Run Go E2E Tests
        run: make test-e2e || (kubectl logs -n kubeflow-system -l app.kubernetes.io/name=trainer && exit 1)
